Changed coz sata cannot be ejected like usb

diff --git a/bin/vm-snap-create b/bin/vm-snap-create
--- a/bin/vm-snap-create
+++ b/bin/vm-snap-create
@@ -5,15 +5,48 @@
 
 BOOTLOADER_FULLPATH="${DISK_PATH%/}/bootloader.raw"
 DEV_TYPE="sata"
+rc=0
+
 [[ "${BOOTLOADER_AS_USB}" == [Yy1]* ]] && DEV_TYPE="usb"
 
-echo "INFO: Creating live snapshot ..."
+echo "#      Creating live snapshot      #"
+echo "# ################################ #"
 
-echo "## INFO: Disabling bootloader disk ..."
-echo "eject drive-${DEV_TYPE}-disk-bootloader" | nc -U /run/qemu-monitor.sock
+echo ""
+echo "#### INFO: Ejecting bootloader ${DEV_TYPE} disk ..."
+[[ "${DEV_TYPE}" == "usb" ]] \
+	&& echo "eject drive-${DEV_TYPE}-disk-bootloader" | nc -U /run/qemu-monitor.sock \
+	|| echo "drive_del drive-${DEV_TYPE}-disk-bootloader" | nc -U /run/qemu-monitor.sock
+echo ""
 
-echo "## INFO: Saving vm ..."
+echo "info block" | nc -U /run/qemu-monitor.sock | grep -q "${BOOTLOADER_FULLPATH}"
+rc=$?
+[[ $rc -ne 0 ]] \
+	&& echo "## INFO: Bootloader ${DEV_TYPE} disk has been ejected successfully." \
+	|| ( echo "## ERROR: Bootloader ${DEV_TYPE} disk has NOT been ejected. Make sure it's not in use!" && exit 1 )
+echo ""
+
+echo ""
+echo "#### INFO: Saving vm ..."
 echo savevm $1 | nc -U /run/qemu-monitor.sock
+echo "" 
 
-echo "## INFO: Renabling bootloader disk ..."
-echo "change drive-${DEV_TYPE}-disk-bootloader ${BOOTLOADER_FULLPATH} ${BOOTLOADER_FULLPATH##*.}" | nc -U /run/qemu-monitor.sock
+echo ""
+echo "#### INFO: Reinserting bootloader ${DEV_TYPE} disk ..."
+if [[ "${DEV_TYPE}" == "usb" ]]; then
+	echo "change drive-${DEV_TYPE}-disk-bootloader ${BOOTLOADER_FULLPATH} ${BOOTLOADER_FULLPATH##*.}" | nc -U /run/qemu-monitor.sock
+else
+	cat <<- __EOF__ | nc -U /run/qemu-monitor.sock
+		drive_add 0 "file=${BOOTLOADER_FULLPATH},if=none,id=drive-${DEV_TYPE}-disk-bootloader,format=${BOOTLOADER_FULLPATH##*.},cache=none,aio=native,detect-zeroes=on"
+		device_add "ide-hd,bus=ahci0.0,drive=drive-${DEV_TYPE}-disk-bootloader,id=sata-disk-bootloader,bootindex=100"
+	__EOF__
+fi
+echo ""
+
+echo "info block" | nc -U /run/qemu-monitor.sock | grep -q "drive-${DEV_TYPE}-disk-bootloader.*${BOOTLOADER_FULLPATH}"
+rc=$?
+[[ $rc -eq 0 ]] && echo "## INFO: Bootloader ${DEV_TYPE} disk has been reinserted successfully..." \
+	|| ( echo "## WARNING: Bootloader ${DEV_TYPE} disk has NOT been reinserted. You may have boot issue on reset." && exit $rc )
+echo ""
+
+exit $rc
